// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SentinelCore.Cfe.Persistence;

[Table("CaseEntity")]
[Index("PatternMemoryId", Name = "FK_CaseEntity", IsUnique = true)]
[Index("InitiatingSignal", Name = "IX_CaseEntity", IsUnique = true)]
[Index("EvidenceId", Name = "UQ_Evidence", IsUnique = true)]
public partial class CaseEntity
{
    [Key]
    public int Id { get; set; }

    public Guid CaseId { get; set; }

    public int Status { get; set; }

    public int InitiatingSignal { get; set; }

    [Precision(2)]
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public DateTime CreatedAt { get; set; }

    [Precision(2)]
    public DateTime? UpdatedAt { get; set; }

    public int? PlanId { get; set; }

    public int? AdditionalSignals { get; set; }

    public int? EvidenceId { get; set; }

    [StringLength(10)]
    public string Remediation { get; set; }

    public int? PatternMemoryId { get; set; }
}