// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SentinelCore.Cfe.Persistence;

[Table("EvidenceEntity")]
public partial class EvidenceEntity
{
    [Key]
    public int Id { get; set; }

    public int EvidenceId { get; set; }

    public string ContentJson { get; set; }

    public string Provenance { get; set; }

    public string Source { get; set; }

    public DateTime Timestamp { get; set; }

    [Required]
    public string Type { get; set; }
}