// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SentinelCore.Persistence;

[Table("InvestigationPlanStepsEntity")]
[Index("StepId", Name = "AK_InvestigationPlanSteps_InvestigationPlanStepId", IsUnique = true)]
public partial class InvestigationPlanStepsEntity
{
    [Key]
    public int Id { get; set; }

    /// <summary>
    /// Links this step the plan it was created in
    /// </summary>
    public int StepId { get; set; }

    public int PlanId { get; set; }

    /// <summary>
    /// Domain or Surface that the task applies to
    /// </summary>
    [Required]
    public string Surface { get; set; }

    [Required]
    public string Instruction { get; set; }

    [Required]
    public string Result { get; set; }

    public bool CompletedSuccessfully { get; set; }

    public bool TaskBlocked { get; set; }

    /// <summary>
    /// If the target of the task is not found this bit must be flipped
    /// </summary>
    public bool IsTargetPropertyMissing { get; set; }
}