// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SentinelCore.Cfe.Persistence;

[Table("InvestigationPlanEntity")]
[Index("PlanId", Name = "AK_InvestigationPlan_InvestigationPlanId", IsUnique = true)]
public partial class InvestigationPlanEntity
{
    [Key]
    public int Id { get; set; }

    public int PlanId { get; set; }

    [Precision(2)]
    public DateTime CreatedAt { get; set; }

    public string Notes { get; set; }
}