// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.Data.SqlTypes;
using Microsoft.EntityFrameworkCore;

namespace SentinelCore.Cfe.Persistence;

[Table("PatternMemoryEntity")]
[Index("PatternId", Name = "AK_PatternMemory_PatternMemoryId", IsUnique = true)]
[Index("CaseId", Name = "IX_PatternMemory_CaseRecordId")]
public partial class PatternMemoryEntity
{
    [Key]
    public int Id { get; set; }

    public int PatternId { get; set; }

    public int CaseId { get; set; }

    [MaxLength(1024)]
    public SqlVector<float>? SignalEmbedding { get; set; }

    [MaxLength(1024)]
    public SqlVector<float>? SummaryEmbedding { get; set; }

    [Required]
    public string Summary { get; set; }

    [Precision(2)]
    public DateTime Timestamp { get; set; }
}