// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SentinelCore.RemoteKB.Persistence;

/// <summary>
/// This table represents all off site knowledge bases available for SentinelCore
/// </summary>
public partial class RemoteSource
{
    [Key]
    public int Id { get; set; }

    [Required]
    [Column("sitealias")]
    [StringLength(50)]
    public string Sitealias { get; set; }

    [Required]
    [Column("url")]
    public string Url { get; set; }

    [Column("title")]
    [StringLength(150)]
    public string Title { get; set; }
}