// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SentinelCore.Cfe.Persistence;

[Table("ResolutionEntity")]
public partial class ResolutionEntity
{
    [Key]
    public int Id { get; set; }

    [Required]
    public string RawJsonContent { get; set; }

    public int CaseRecordId { get; set; }

    public string Notes { get; set; }

    [Precision(2)]
    public DateTime? CreatedAt { get; set; }

    public bool Verified { get; set; }
}