// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

using SentinelCore.Persistence;




namespace SentinelCore.Cfe.Persistence;

public partial class SentinelCoreDBContext : DbContext
{
    public SentinelCoreDBContext()
    {
    }

    public SentinelCoreDBContext(DbContextOptions<SentinelCoreDBContext> options)
        : base(options)
    {
    }

    public virtual DbSet<InvestigationPlanStepsEntity> InvestigationPlanStepsEntities { get; set; }

    public virtual DbSet<PatternMemoryEntity> PatternMemoryEntities { get; set; }

    public virtual DbSet<ResolutionEntity> ResolutionEntities { get; set; }

    public virtual DbSet<SignalEntity> SignalEntities { get; set; }

    public virtual DbSet<CaseEntity> CaseEntities { get; set; }

    public virtual DbSet<EvidenceEntity> EvidenceEntities { get; set; }         








    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
#warning To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see https://go.microsoft.com/fwlink/?LinkId=723263.
        => optionsBuilder.UseSqlServer("Data Source=Desktop-NC01091;Initial Catalog=SentinelCore;Integrated Security=True;Encrypt=False");

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<InvestigationPlanStepsEntity>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK_InvestigationPlanSteps");

            entity.Property(e => e.CompletedSuccessfully).HasDefaultValue(false, "DF_InvestigationPlanStepsEntities_CompletedSuccessfully");
            entity.Property(e => e.IsTargetPropertyMissing)
                .HasComment("If the target of the task is not found this bit must be flipped")
                .HasDefaultValue(false, "DF_InvestigationPlanStepsEntities_IsTargetPropertyMissing");
            entity.Property(e => e.StepId).HasComment("Links this step the plan it was created in");
            entity.Property(e => e.Surface).HasComment("Domain or Surface that the task applies to");
            entity.Property(e => e.TaskBlocked).HasDefaultValue(false, "DF_InvestigationPlanStepsEntities_TaskBlocked");
        });

        modelBuilder.Entity<PatternMemoryEntity>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK_PatternMemory");
        });

        modelBuilder.Entity<ResolutionEntity>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK_ResolutionSteps");

            entity.Property(e => e.Verified).HasDefaultValue(false, "DF_ResolutionSteps_Verified");
        });

        modelBuilder.Entity<SignalEntity>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK_Signals");
        });
        modelBuilder.Entity<SignalEntity>().Property(e=>e.SignalId).ValueGeneratedOnAdd()
                .HasDefaultValueSql("NEXT VALUE FOR [dbo].[Signal_ID_seq]");

        modelBuilder.Entity<CaseEntity>(entity =>
        {
            entity.Property(e => e.CreatedAt).HasDefaultValueSql("GETDATE()");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}