// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace SentinelCore.RemoteKB.Persistence;

public partial class SentinelRAGDBContext : DbContext
{
    public SentinelRAGDBContext()
    {
    }

    public SentinelRAGDBContext(DbContextOptions<SentinelRAGDBContext> options)
        : base(options)
    {
    }

    public virtual DbSet<RemoteSource> RemoteSources { get; set; }

    public virtual DbSet<SourceDoc> SourceDocs { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
    }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<RemoteSource>(entity =>
        {
            entity.ToTable(tb => tb.HasComment("This table represents all off site knowledge bases available for SentinelCore"));
        });

        modelBuilder.Entity<SourceDoc>(entity =>
        {
            entity.HasKey(e => e.DocumentId).HasName("PK_WinDocsHub");
        });

        OnModelCreatingGeneratedFunctions(modelBuilder);
        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}
