// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace SentinelCore.CaseFlowEngine.Persistence;

public partial class SentinelCoreDBContext : DbContext
{
    
    
    
    
    
    
    public SentinelCoreDBContext()
    {
    }

    public SentinelCoreDBContext(DbContextOptions<SentinelCoreDBContext> options)
        : base(options)
    {
    }

    public virtual DbSet<CaseEntity> CaseEntities { get; set; }

    public virtual DbSet<EvidenceEntity> EvidenceEntities { get; set; }

    public virtual DbSet<InvestigationPlanEntity> InvestigationPlanEntities { get; set; }

    public virtual DbSet<InvestigationPlanStepsEntity> InvestigationPlanStepsEntities { get; set; }

    public virtual DbSet<PatternMemoryEntity> PatternMemoryEntities { get; set; }

    public virtual DbSet<ResolutionEntity> ResolutionEntities { get; set; }

    public virtual DbSet<SignalEntity> SignalEntities { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        // When the context is created by DI, the connection string is already supplied
        // via DbContextOptions and must not be overridden here. Only configure a fallback
        // when no options have been set (e.g., design-time tooling).
        if (!optionsBuilder.IsConfigured)
        {
            optionsBuilder.UseSqlServer();
        }
    }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<CaseEntity>(entity =>
        {
            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(getdate())", "DF_CaseEntities_CreatedAt");
            entity.Property(e => e.Remediation).IsFixedLength();
        });

        modelBuilder.Entity<EvidenceEntity>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK_EvidenceRecords");

            entity.Property(e => e.EvidenceId).HasDefaultValueSql("(NEXT VALUE FOR [EvidenceRecordIdSeq])", "DF__EvidenceE__Evide__6477ECF3");
        });

        modelBuilder.Entity<InvestigationPlanEntity>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK_InvestigationPlan");

            entity.Property(e => e.PlanId).HasDefaultValueSql("(NEXT VALUE FOR [InvestigationPlanIdSeq])", "DF__Investiga__Inves__6E01572D");
        });

        modelBuilder.Entity<InvestigationPlanStepsEntity>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK_InvestigationPlanSteps");

            entity.Property(e => e.IsTargetPropertyMissing).HasComment("If the target of the task is not found this bit must be flipped");
            entity.Property(e => e.StepId)
                .HasComment("Links this step the plan it was created in")
                .HasDefaultValueSql("(NEXT VALUE FOR [InvestigationPlanStepIdSeq])", "DF__Investiga__Inves__7C4F7684");
            entity.Property(e => e.Surface).HasComment("Domain or Surface that the task applies to");
        });

        modelBuilder.Entity<PatternMemoryEntity>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK_PatternMemory");

            entity.Property(e => e.PatternId).HasDefaultValueSql("(NEXT VALUE FOR [PatternMemoryIdSeq])", "DF__PatternMe__Patte__72C60C4A");
        });

        modelBuilder.Entity<ResolutionEntity>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK_ResolutionSteps");
        });

        modelBuilder.Entity<SignalEntity>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK_Signals");

            entity.Property(e => e.SignalId).HasDefaultValueSql("(NEXT VALUE FOR [SignalIdSeq])");
        });
        modelBuilder.HasSequence<int>("CaseRecordIdSeq");
        modelBuilder.HasSequence<int>("EvidenceRecordIdSeq");
        modelBuilder.HasSequence<int>("InvestigationPlanIdSeq");
        modelBuilder.HasSequence<int>("InvestigationPlanStepIdSeq");
        modelBuilder.HasSequence<int>("PatternMemoryIdSeq");
        modelBuilder.HasSequence<int>("SignalIdSeq");

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}