// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using SentinelCore.RemoteKB.Persistence;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace SentinelCore.RemoteKB.Persistence
{
    public partial class SentinelRAGDBContext
    {
        private ISentinelRAGDBContextProcedures _procedures;

        public virtual ISentinelRAGDBContextProcedures Procedures
        {
            get
            {
                if (_procedures is null) _procedures = new SentinelRAGDBContextProcedures(this);
                return _procedures;
            }
            set
            {
                _procedures = value;
            }
        }

        public ISentinelRAGDBContextProcedures GetProcedures()
        {
            return Procedures;
        }
    }

    public partial class SentinelRAGDBContextProcedures : ISentinelRAGDBContextProcedures
    {
        private readonly SentinelRAGDBContext _context;

        public SentinelRAGDBContextProcedures(SentinelRAGDBContext context)
        {
            _context = context;
        }
    }
}
