// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SentinelCore.Cfe.Persistence;

[Table("SignalEntity")]
[Index("SignalId", Name = "AK_Signals_SignalId", IsUnique = true)]
public partial class SignalEntity
{
    [Key]
    public int Id { get; set; }

    public int SignalId { get; set; }

    [Required]
    public string SignalText { get; set; }

    [Required]
    public string Source { get; set; }

    public DateTime Timestamp { get; set; }

    public string Notes { get; set; }
}