// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.Data.SqlTypes;
using Microsoft.EntityFrameworkCore;

namespace SentinelCore.RemoteKB.Persistence;

[Table("SourceDoc")]
[Index("SourceId", "PageUrl", Name = "IX_WinDocsHub_SourceId_PageUrl")]
[Index("PageUrl", Name = "UQ_WinDocsHub_PageURL", IsUnique = true)]
[Index("SummaryEmbedding", Name = "VectorIndex-20260908-143925")]
public partial class SourceDoc
{
    [Key]
    public int DocumentId { get; set; }

    public int SourceId { get; set; }

    [Required]
    public string Title { get; set; }

    [StringLength(250)]
    public string MarkdownUrl { get; set; }

    public string GeneratedSummary { get; set; }

    public string Keywords { get; set; }

    public DateTime? DocLastUpdated { get; set; }

    [MaxLength(1024)]
    public SqlVector<float>? SummaryEmbedding { get; set; }

    [Required]
    public string PageUrl { get; set; }
}