<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0-windows</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<PackageId>SentinelCore.Orchestrations</PackageId>
		<!--Must use the Rootnamespace to keep all projects properly aligned and visible DO NOT CHANGE-->
		<RootNamespace>SentinelCore</RootNamespace>
	</PropertyGroup>

	<ItemGroup>
		<InternalsVisibleTo Include="SentinelCore.Tests" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\SentinelCore.CaseFlowEngine\SentinelCore.CaseFlowEngine.csproj" />
		<ProjectReference Include="..\SentinelCore.Contracts\SentinelCore.Contracts.csproj" />
		<PackageReference Include="Microsoft.Agents.AI" />
		<PackageReference Include="Microsoft.Agents.AI.Abstractions" />
		<PackageReference Include="ModelContextProtocol" />
		<PackageReference Include="Microsoft.Agents.AI.Mcp" />
		<PackageReference Include="Microsoft.Agents.AI.Workflows" />
		<PackageReference Include="Microsoft.Agents.AI.Workflows.Generators">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.Extensions.AI" />
		<PackageReference Include="Microsoft.Extensions.AI.Abstractions" />
		<PackageReference Include="Azure.AI.OpenAI" />
		<PackageReference Include="Microsoft.Extensions.AI.OpenAI" />
		<PackageReference Include="OpenAI" />
		<PackageReference Include="Jetbrains.Annotations" />
		<PackageReference Include="Microsoft.Extensions.DependencyInjection" />
		<PackageReference Include="Microsoft.Extensions.Hosting" />
		<PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
		<PackageReference Include="Microsoft.Extensions.Logging" />
		<PackageReference Include="Microsoft.Extensions.Logging.Console" />
		<PackageReference Include="Microsoft.EntityFrameworkCore" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" />
		<PackageReference Include="Microsoft.Management.Infrastructure" />
		<PackageReference Include="Microsoft.Windows.Compatibility" />
		<PackageReference Include="OllamaSharp" />
		<PackageReference Include="System.DirectoryServices.AccountManagement" />
		<PackageReference Include="System.Management" />
		<PackageReference Include="System.Management.Automation" />
		<PackageReference Include="System.ServiceProcess.ServiceController" />
		<PackageReference Include="TaskScheduler" />


<None Include="SentinelCoreMCP.exe" CopyToOutputDirectory="PreserveNewest" />
	</ItemGroup>

</Project>
