// <auto-generated />
using System;
using Microsoft.Data.SqlTypes;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SentinelCore.Cfe.Persistence;

#nullable disable

namespace SentinelCore.Migrations
{
    [DbContext(typeof(SentinelCoreDBContext))]
    partial class SentinelCoreDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SentinelCore.Cfe.Persistence.CaseEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AdditionalSignals")
                        .HasColumnType("int");

                    b.Property<Guid>("CaseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(2)
                        .HasColumnType("datetime2(2)")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int?>("EvidenceId")
                        .HasColumnType("int");

                    b.Property<int>("InitiatingSignal")
                        .HasColumnType("int");

                    b.Property<int?>("PatternMemoryId")
                        .HasColumnType("int");

                    b.Property<int?>("PlanId")
                        .HasColumnType("int");

                    b.Property<string>("Remediation")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasPrecision(2)
                        .HasColumnType("datetime2(2)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "PatternMemoryId" }, "FK_CaseEntity")
                        .IsUnique()
                        .HasFilter("[PatternMemoryId] IS NOT NULL");

                    b.HasIndex(new[] { "InitiatingSignal" }, "IX_CaseEntity")
                        .IsUnique();

                    b.HasIndex(new[] { "EvidenceId" }, "UQ_Evidence")
                        .IsUnique()
                        .HasFilter("[EvidenceId] IS NOT NULL");

                    b.ToTable("CaseEntity");
                });

            modelBuilder.Entity("SentinelCore.Cfe.Persistence.EvidenceEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ContentJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EvidenceId")
                        .HasColumnType("int");

                    b.Property<string>("Provenance")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Source")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("EvidenceEntity");
                });

            modelBuilder.Entity("SentinelCore.Cfe.Persistence.PatternMemoryEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CaseId")
                        .HasColumnType("int");

                    b.Property<int>("PatternId")
                        .HasColumnType("int");

                    b.Property<SqlVector<float>?>("SignalEmbedding")
                        .HasMaxLength(1024)
                        .HasColumnType("vector(1024)");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<SqlVector<float>?>("SummaryEmbedding")
                        .HasMaxLength(1024)
                        .HasColumnType("vector(1024)");

                    b.Property<DateTime>("Timestamp")
                        .HasPrecision(2)
                        .HasColumnType("datetime2(2)");

                    b.HasKey("Id")
                        .HasName("PK_PatternMemory");

                    b.HasIndex(new[] { "PatternId" }, "AK_PatternMemory_PatternMemoryId")
                        .IsUnique();

                    b.HasIndex(new[] { "CaseId" }, "IX_PatternMemory_CaseRecordId");

                    b.ToTable("PatternMemoryEntity");
                });

            modelBuilder.Entity("SentinelCore.Cfe.Persistence.ResolutionEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CaseRecordId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedAt")
                        .HasPrecision(2)
                        .HasColumnType("datetime2(2)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RawJsonContent")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Verified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false, "DF_ResolutionSteps_Verified");

                    b.HasKey("Id")
                        .HasName("PK_ResolutionSteps");

                    b.ToTable("ResolutionEntity");
                });

            modelBuilder.Entity("SentinelCore.Persistence.InvestigationPlanStepsEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("CompletedSuccessfully")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false, "DF_InvestigationPlanStepsEntities_CompletedSuccessfully");

                    b.Property<string>("Instruction")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsTargetPropertyMissing")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasComment("If the target of the task is not found this bit must be flipped")
                        .HasDefaultValue(false, "DF_InvestigationPlanStepsEntities_IsTargetPropertyMissing");

                    b.Property<int>("PlanId")
                        .HasColumnType("int");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StepId")
                        .HasColumnType("int")
                        .HasComment("Links this step the plan it was created in");

                    b.Property<string>("Surface")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasComment("Domain or Surface that the task applies to");

                    b.Property<bool>("TaskBlocked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false, "DF_InvestigationPlanStepsEntities_TaskBlocked");

                    b.HasKey("Id")
                        .HasName("PK_InvestigationPlanSteps");

                    b.HasIndex(new[] { "StepId" }, "AK_InvestigationPlanSteps_InvestigationPlanStepId")
                        .IsUnique();

                    b.ToTable("InvestigationPlanStepsEntity");
                });

            modelBuilder.Entity("SentinelCore.Persistence.SignalEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SignalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("NEXT VALUE FOR [dbo].[Signal_ID_seq]");

                    b.Property<string>("SignalText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id")
                        .HasName("PK_Signals");

                    b.HasIndex(new[] { "SignalId" }, "AK_Signals_SignalId")
                        .IsUnique();

                    b.ToTable("SignalEntity");
                });
#pragma warning restore 612, 618
        }
    }
}
