// Solution: SentinelCore
// Project:   SentinelCore.Contracts
// File:         IMcpServerRegistryStore.cs
// Author: Generated by GitHub Copilot

namespace SentinelCore.Mcp;

/// <summary>
///     Persists and loads registered MCP server definitions.
/// </summary>
public interface IMcpServerRegistryStore
{
    /// <summary>
    ///     Loads persisted server definitions.
    /// </summary>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>
    ///     A task that resolves to a read-only list of persisted server definitions.
    ///     Returns an empty list when no persisted data is available.
    /// </returns>
    Task<IReadOnlyList<McpServerDefinition>> LoadAsync(CancellationToken cancellationToken = default);

    /// <summary>
    ///     Saves the provided server definitions.
    /// </summary>
    /// <param name="definitions">Server definitions to persist.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>A task that represents the asynchronous save operation.</returns>
    Task SaveAsync(IReadOnlyList<McpServerDefinition> definitions, CancellationToken cancellationToken = default);
}
