// Solution: SentinelCore
// Project:   SentinelCore.Orchestrations
// File:         McpConnectionFactory.cs
// Author: Generated by GitHub Copilot

using System.Security.Cryptography;
using System.Text;

using Microsoft.Extensions.Logging;

using ModelContextProtocol.Authentication;
using ModelContextProtocol.Client;

using SentinelCore.Mcp;

namespace SentinelCore.Orchestrations.Mcp;

/// <summary>
///     Creates <see cref="McpClient" /> connections backed by stdio or HTTP transports,
///     with optional OAuth configuration for protected HTTP endpoints.
/// </summary>
public sealed class McpConnectionFactory : IMcpConnectionFactory
{
    private readonly ILoggerFactory _loggerFactory;
    private readonly ITokenCache? _tokenCache;

    /// <summary>
    ///     Initializes a new instance of the <see cref="McpConnectionFactory" /> class.
    /// </summary>
    /// <param name="loggerFactory">The logger factory used by MCP transports and clients.</param>
    /// <param name="tokenCache">Optional token cache for OAuth token storage.</param>
    public McpConnectionFactory(ILoggerFactory loggerFactory, ITokenCache? tokenCache = null)
    {
        ArgumentNullException.ThrowIfNull(loggerFactory);

        _loggerFactory = loggerFactory;
        _tokenCache = tokenCache;
    }

    /// <inheritdoc />
    public async Task<McpClient> ConnectAsync(McpServerDefinition definition, CancellationToken cancellationToken = default)
    {
        ArgumentNullException.ThrowIfNull(definition);

        IClientTransport transport = definition.TransportType switch
        {
            McpServerTransportType.Stdio => CreateStdioTransport(definition),
            McpServerTransportType.Http => CreateHttpTransport(definition),
            _ => throw new InvalidOperationException($"Unsupported MCP transport type: {definition.TransportType}.")
        };

        McpClientOptions clientOptions = new()
        {
            ClientInfo = new() { Name = "SentinelCore", Version = "1.0.0" }
        };

        McpClient client = await McpClient
            .CreateAsync(transport, clientOptions, _loggerFactory, cancellationToken)
            .ConfigureAwait(false);

        return client;
    }

    private IClientTransport CreateStdioTransport(McpServerDefinition definition)
    {
        if (string.IsNullOrWhiteSpace(definition.CommandOrEndpoint))
        {
            throw new InvalidOperationException("Stdio MCP server requires a command.");
        }

        Dictionary<string, string> environment = new(StringComparer.OrdinalIgnoreCase);

        if (definition.EnvironmentVariables is not null)
        {
            foreach (KeyValuePair<string, string> entry in definition.EnvironmentVariables)
            {
                environment[entry.Key] = entry.Value;
            }
        }

        StdioClientTransportOptions options = new()
        {
            Command = definition.CommandOrEndpoint,
            Arguments = definition.Arguments?.ToList(),
            WorkingDirectory = definition.WorkingDirectory,
            EnvironmentVariables = environment.ToDictionary(static e => e.Key, static e => (string?)e.Value),
            Name = definition.DisplayName ?? definition.Id
        };

        return new StdioClientTransport(options, _loggerFactory);
    }

    private IClientTransport CreateHttpTransport(McpServerDefinition definition)
    {
        if (string.IsNullOrWhiteSpace(definition.CommandOrEndpoint))
        {
            throw new InvalidOperationException("HTTP MCP server requires an endpoint URI.");
        }

        if (!Uri.TryCreate(definition.CommandOrEndpoint, UriKind.Absolute, out Uri? endpoint))
        {
            throw new InvalidOperationException($"Invalid HTTP MCP server endpoint: '{definition.CommandOrEndpoint}'.");
        }

        HttpClientTransportOptions options = new()
        {
            Endpoint = endpoint,
            Name = definition.DisplayName ?? definition.Id
        };

        if (definition.OAuthSettings is not null)
        {
            options.OAuth = CreateOAuthOptions(definition.OAuthSettings);
        }

        return new HttpClientTransport(options, _loggerFactory);
    }

    private ClientOAuthOptions CreateOAuthOptions(McpOAuthSettings settings)
    {
        ArgumentNullException.ThrowIfNull(settings);

        ClientOAuthOptions options = new()
        {
            RedirectUri = string.IsNullOrWhiteSpace(settings.CallbackUri)
                ? new Uri("http://127.0.0.1:0/")
                : new Uri(settings.CallbackUri),
            ClientId = settings.ClientId,
            Scopes = string.IsNullOrWhiteSpace(settings.Scopes)
                ? null
                : settings.Scopes.Split(' ', StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries)
        };

        if (_tokenCache is not null)
        {
            options.TokenCache = _tokenCache;
        }

        options.AuthorizationCallbackHandler = LoopbackOAuthCallbackHandler.Create(options.RedirectUri);

        return options;
    }
}
