// Solution: SentinelCore
// Project:   SentinelCore.Orchestrations
// File:         AgentExecutor.cs
// Author: Kyle L. Crowder
// Build Num:  082808



namespace SentinelCore.Workflows.Executors;





public class ClassifierAgentExec(AIAgent agent) : Executor<ChatMessage, SignalHypothesis>("ClassifierExec")
{

    /// <summary>
    ///     Handles the processing of a <see cref="ChatMessage" /> within the workflow context
    ///     and returns a <see cref="SignalHypothesis" /> as the result.
    /// </summary>
    /// <param name="message">
    ///     The <see cref="ChatMessage" /> to be processed by the agent.
    /// </param>
    /// <param name="context">
    ///     The workflow context implementing <see cref="IWorkflowContext" />, which provides
    ///     the necessary environment for the execution.
    /// </param>
    /// <param name="cancellationToken">
    ///     A <see cref="CancellationToken" /> to observe while waiting for the task to complete.
    /// </param>
    /// <returns>
    ///     A task that represents the asynchronous operation. The task result contains the
    ///     <see cref="SignalHypothesis" /> generated by the agent, or <c>null</c> if no result is produced.
    /// </returns>
    /// <remarks>
    ///     This method invokes the agent to process the input message, validates the response,
    ///     and sends the resulting hypothesis back to the workflow context. Additionally, it updates
    ///     the shared state with the hypothesis data for use by other actors in the workflow.
    /// </remarks>
    public override async ValueTask<SignalHypothesis> HandleAsync(ChatMessage message, IWorkflowContext context, CancellationToken cancellationToken = new())
    {
        string json = "";
        AgentResponse<SignalHypothesis> response = await agent.RunAsync<SignalHypothesis>(message, cancellationToken: cancellationToken).ConfigureAwait(false);
        if (response.Text.StartsWith("```json"))
        {

            json = response.Text.TrimStart("```json").TrimEnd("```").ToString();
        }

        // Saves the value in a special shared state bag so it may be shared with all actors in the workflow.
        await context.QueueStateUpdateAsync(WorkFlowStateKeys.SIGNAL_HYPOTHESIS, json, "SharedState", cancellationToken).ConfigureAwait(false);

        // An invalid json response will cause the Result prop to throw, validate before using.
        return response.Result;
    }
}