// Solution: SentinelCore
// Project:   SentinelCore.Orchestrations
// File:         ClassifierAgentExec.cs
// Author: Kyle L. Crowder
// Build Num:  091418



using System.Diagnostics;




namespace SentinelCore.Orchestrations.Workflows.Executors;





public sealed class ClassifierAgentExec(AIAgent agent) : Executor<ChatMessage, SignalHypothesis>("ClassifierExec")
{

    /// <summary>
    ///     Handles the processing of a <see cref="ChatMessage" /> within the main investigation workflow.
    ///     This executor is responsible for directing the traffic for the first major junction in the graph.
    ///     This agent does not actually do anything with the message but decide where it is to go next.
    ///     and returns a <see cref="SignalHypothesis" /> as the result.
    ///     This is where TheCore processes the signal and generates the initial hypothesis.
    /// </summary>
    /// <param name="message">
    ///     The <see cref="ChatMessage" /> to be processed by the agent.
    /// </param>
    /// <param name="context">
    ///     The workflow context implementing <see cref="IWorkflowContext" />, which provides
    ///     the necessary environment for the execution.
    /// </param>
    /// <param name="cancellationToken">
    ///     A <see cref="CancellationToken" /> to observe while waiting for the task to complete.
    /// </param>
    /// <returns>
    ///     A task that represents the asynchronous operation. The task result contains the
    ///     <see cref="SignalHypothesis" /> generated by the agent, or <c>null</c> if no result is produced.
    /// </returns>
    /// <remarks>
    ///     This method invokes the agent to process the input message, validates the response.
    ///     then the agent will set the NextStep property of the SignalHypothesis to indicate the next step in the workflow,
    ///     To keep steps deterministic we will no longer have this agent generate the hypothesis, but instead have it generate
    ///     the next step in the workflow.
    ///     The hypothesis will be generated by the next agent in the workflow which will be this same instance of the AIAgent,
    ///     but without a persistent context.
    ///     The agent won't get a context and no possible contamination of the workflow will occur. The agent will generate the
    ///     hypothesis and return it to the workflow context.
    ///     Additionally, it makes use of the shared state and passes data for use by other actors in the workflow.
    ///     NOTE: TheCore agent is the only agent to have a full persistent context. The Magnetic sub-workflow will have a
    ///     context that lives for the duration of the sub-workflow, but it will not be persisted across multiple runs of the
    ///     workflow.
    /// </remarks>
    public override async ValueTask<SignalHypothesis> HandleAsync(ChatMessage message, IWorkflowContext context, CancellationToken cancellationToken = new())
    {
        AgentResponse<SignalHypothesis>? response = null;

        string json = "";
        try
        {
            response = await agent.RunAsync<SignalHypothesis>(message, cancellationToken: cancellationToken).ConfigureAwait(false);
            if (response.Text.StartsWith("```json"))
            {
                json = response.Text.Replace("```json", "").Replace("```", "").Trim();
            }




            if (response == null)
            {
                throw new InvalidOperationException("Agent response is null.");
            }




        }
        catch (Exception e)
        {
            //log and go
            Debug.Print(e.Message);
        }

        // Saves the value in a special shared state bag so it may be shared with all actors in the workflow.
        await context.QueueStateUpdateAsync(WorkFlowStateKeys.SIGNAL_HYPOTHESIS, json, "SharedState", cancellationToken).ConfigureAwait(false);

        // An invalid json response will cause the Result prop to throw, validate before using.
        return response.Result;
    }
}