// Solution: SentinelCore
// Project:   SentinelCore.Orchestrations
// File:         ClassifierAgentExec.cs
// Author: Kyle L. Crowder
// Build Num:  091418



using SentinelCore.Contracts.Abstractions;




namespace SentinelCore.Orchestrations.Workflows.Executors;





/// <summary>
///     Classifies an incoming signal and routes it by returning a <see cref="SignalHypothesis" />.
///     On classification failure the handler yields a user-visible <see cref="ChatMessage" />
///     notice before returning a fallback hypothesis routed to human review.
/// </summary>
/// <param name="agent">The classifier agent.</param>
/// <param name="reporter">The system reporter for logging.</param>
[YieldsOutput(typeof(ChatMessage))]
public sealed partial class ClassifierAgentExec(AIAgent agent, ISystemReporter reporter) : Executor<ChatMessage, SignalHypothesis>("ClassifierExec")
{



    /// <summary>
    ///     Handles the processing of a <see cref="ChatMessage" /> within the main investigation workflow.
    ///     This executor is responsible for directing the traffic for the first major junction in the graph.
    ///     This agent does not actually do anything with the message but decide where it is to go next.
    ///     and returns a <see cref="SignalHypothesis" /> as the result.
    ///     This is where TheCore processes the signal and generates the initial hypothesis.
    /// </summary>
    /// <param name="message">
    ///     The <see cref="ChatMessage" /> to be processed by the agent.
    /// </param>
    /// <param name="context">
    ///     The workflow context implementing <see cref="IWorkflowContext" />, which provides
    ///     the necessary environment for the execution.
    /// </param>
    /// <param name="cancellationToken">
    ///     A <see cref="CancellationToken" /> to observe while waiting for the task to complete.
    /// </param>
    /// <returns>
    ///     A task that represents the asynchronous operation. The task result contains the
    ///     <see cref="SignalHypothesis" /> generated by the agent. When classification fails,
    ///     the result is a fallback hypothesis explicitly routed to
    ///     <see cref="NextStep.EscalateToHumanOperator" /> — never the <see cref="NextStep.RedAlert" /> enum default.
    /// </returns>
    /// <remarks>
    ///     This method invokes the agent to process the input message, validates the response.
    ///     then the agent will set the NextStep property of the SignalHypothesis to indicate the next step in the workflow,
    ///     To keep steps deterministic we will no longer have this agent generate the hypothesis, but instead have it generate
    ///     the next step in the workflow.
    ///     The hypothesis will be generated by the next agent in the workflow which will be this same instance of the AIAgent,
    ///     but without a persistent context.
    ///     The agent won't get a context and no possible contamination of the workflow will occur. The agent will generate the
    ///     hypothesis and return it to the workflow context.
    ///     Additionally, it makes use of the shared state and passes data for use by other actors in the workflow.
    ///     NOTE: TheCore agent is the only agent to have a full persistent context. The Magnetic sub-workflow will have a
    ///     context that lives for the duration of the sub-workflow, but it will not be persisted across multiple runs of the
    ///     workflow.
    /// </remarks>
    public override async ValueTask<SignalHypothesis> HandleAsync(ChatMessage message, IWorkflowContext context, CancellationToken cancellationToken = new())
    {
        reporter.ReportInfo("Starting classifier handler");

        await context.QueueStateUpdateAsync(WorkFlowStateKeys.PROMPT, message.Text, "SharedState", cancellationToken).ConfigureAwait(false);
        try
        {
            AgentResponse<SignalHypothesis> response = await agent.RunAsync<SignalHypothesis>(message, cancellationToken: cancellationToken).ConfigureAwait(false);

            if (response.Result is null)
            {
                await context.YieldOutputAsync(new ChatMessage(ChatRole.User, "Agent did not return a response, retry request in a bit."),cancellationToken);
            }

            // Copy the result and attach the original prompt so downstream
            // executors can recall what the user actually asked.
            SignalHypothesis returnObj = response.Result;
            returnObj.OrigPrompt = message.Text;

            await context.YieldOutputAsync(message, cancellationToken).ConfigureAwait(false);
            return returnObj;


        }
        catch (OperationCanceledException)
        {
            // Cooperative cancellation must propagate — swallowing it here would
            // break user-initiated cancel and application shutdown.
            throw;
        }
        catch (Exception ex)
        {
            // Classification failed. Report it, surface a user-visible message, and
            // route the signal to the human-operator escalation branch — a system
            // error requiring human intervention per the documented semantics of
            // EscalateToHumanOperator. Never fall back to the enum default (RedAlert):
            // a transient model failure is not a critical security event.
            reporter.ReportError($"Classifier failed: {ex.Message}", ex);

            await context.YieldOutputAsync(new ChatMessage(ChatRole.Assistant, $"⚠️ Signal classification failed: {ex.Message} The signal has been routed for human review."), cancellationToken).ConfigureAwait(false);

            return new SignalHypothesis { NextStep = NextStep.EscalateToHumanOperator, OrigPrompt = message.Text, Reasoning = $"Routed by fallback: classifier failed with '{ex.Message}'." };
        }


    }



}
