// Solution: SentinelCore
// Project:   SentinelCore.Orchestrations
// File:         ClassifierAgentExec.cs
// Author: Kyle L. Crowder
// Build Num:  092308



using SentinelCore.Contracts.Abstractions;
using SentinelCore.Orchestrations.Agents;
using SentinelCore.Orchestrations.Agents.Models;




namespace SentinelCore.Orchestrations.Workflows.Executors;





/// <summary>
///     Classifies an incoming signal and routes it by returning a <see cref="SignalHypothesis" />.
///     On classification failure the handler yields a user-visible <see cref="ChatMessage" />
///     notice before returning a fallback hypothesis routed to human review.
/// </summary>
[YieldsOutput(typeof(ChatMessage))]
[YieldsOutput(typeof(SignalHypothesis))]
public sealed partial class ClassifierAgentExec : Executor
{
    private readonly AIAgent _agent;
    private readonly ISystemReporter _reporter;








    /// <summary>
    ///     Initializes a new instance of the <see cref="ClassifierAgentExec" /> class.
    /// </summary>
    /// <param name="agent">The classifier agent.</param>
    /// <param name="reporter">The system reporter for logging.</param>
    public ClassifierAgentExec(AIAgent agent, ISystemReporter reporter) : base("ClassifierExec")
    {
        _agent = agent ?? throw new ArgumentNullException(nameof(agent));
        _reporter = reporter ?? throw new ArgumentNullException(nameof(reporter));
        Name = Id;
    }








    /// <summary>
    ///     Gets the human-readable name of this executor, used in log messages and diagnostics.
    /// </summary>
    public string Name { get; init; }








    /// <summary>
    ///     Creates a fallback result when the executor encounters an error or receives null input.
    /// </summary>
    private SignalHypothesis CreateFallbackResult(string? prompt = null, string? reasoning = null) => new() { NextStep = NextStep.EscalateToHumanOperator, OrigPrompt = prompt ?? string.Empty, Reasoning = reasoning ?? "Fallback: classifier did not produce a result." };








    /// <summary>
    ///     Handles the classification of an incoming signal and routes it by returning a <see cref="SignalHypothesis" />.
    ///     Provides uniform cross-cutting concerns: logging, null validation,
    ///     cooperative cancellation propagation, and structured error handling.
    /// </summary>
    /// <param name="message">The <see cref="ChatMessage" /> to be processed by the agent.</param>
    /// <param name="context">The workflow context implementing <see cref="IWorkflowContext" />.</param>
    /// <param name="cancellationToken">A <see cref="CancellationToken" /> to observe while waiting for the task to complete.</param>
    /// <returns>
    ///     A <see cref="SignalHypothesis" /> generated by the agent. When classification fails,
    ///     the result is a fallback hypothesis explicitly routed to
    ///     <see cref="NextStep.EscalateToHumanOperator" /> — never the <see cref="NextStep.RedAlert" /> enum default.
    /// </returns>
    [MessageHandler]
    public async ValueTask<SignalHypothesis> HandleChatMessageAsync(ChatMessage? message, IWorkflowContext context, CancellationToken cancellationToken = default)
    {
        // --- Status: Executor start ---
        _reporter.ReportInfo($"[{Name}] Starting execution. Input type: {typeof(ChatMessage).Name}");

        // --- Null validation ---
        if (message is null)
        {
            _reporter.ReportError($"[{Name}] Input message was null. Returning fallback {nameof(SignalHypothesis)}.");
            await context.YieldOutputAsync(new ChatMessage(ChatRole.Assistant, $"[{Name}] Input message was null. Returning fallback {nameof(SignalHypothesis)}."), cancellationToken).ConfigureAwait(false);
            return CreateFallbackResult(message?.Text);
        }

        try
        {
            // --- Status: Begin processing ---
            _reporter.ReportInfo($"[{Name}] Processing message...");

            SignalHypothesis result = await ProcessMessageAsync(message, context, cancellationToken).ConfigureAwait(false);

            if (result is null)
            {
                _reporter.ReportError($"[{Name}] ProcessMessageAsync returned null. Using fallback {nameof(SignalHypothesis)}.");
                result = CreateFallbackResult(message.Text);
            }

            // --- Status: Final output ---
            _reporter.ReportInfo($"[{Name}] Completed successfully. Output type: {nameof(SignalHypothesis)}");

            return result;
        }
        catch (OperationCanceledException)
        {
            // Cooperative cancellation must propagate — never swallow it.
            _reporter.ReportInfo($"[{Name}] Execution canceled.");
            throw;
        }
        catch (Exception ex)
        {
            // --- Robust error handling ---
            // Classification failed. Route to human-operator escalation — a system
            // error requiring human intervention. Never fall back to RedAlert:
            // a transient model failure is not a critical security event.
            _reporter.ReportError($"[{Name}] Exception: {ex.Message}", ex);

            await context.YieldOutputAsync(new ChatMessage(ChatRole.Assistant, $"⚠️ Signal classification failed: {ex.Message} The signal has been routed for human review."), cancellationToken).ConfigureAwait(false);

            _reporter.ReportInfo($"[{Name}] Returning fallback {nameof(SignalHypothesis)} due to error.");

            return CreateFallbackResult(message.Text, $"Routed by fallback: classifier failed with '{ex.Message}'.");
        }
    }








    /// <summary>
    ///     Core processing logic: invokes the classifier agent and attaches the original prompt.
    /// </summary>
    private async ValueTask<SignalHypothesis> ProcessMessageAsync(ChatMessage message, IWorkflowContext context, CancellationToken cancellationToken)
    {
        _reporter.ReportInfo($"[{Name}] Starting classifier handler");
        ChatMessages msg = new();
        msg.AddSystemMessage(AgentInstructionConstants.CURRENT_PLATFORM_DOMAIN_S);
        msg.AddSystemMessage(AgentInstructionConstants.CLASSIFIER_INSTRUCTIONS);
        msg.AddUserMessage(message.Text);



        await context.QueueStateUpdateAsync(WorkFlowStateKeys.PROMPT, message.Text, "SharedState", cancellationToken).ConfigureAwait(false);

        AgentResponse<SignalHypothesis> response = await _agent.RunAsync<SignalHypothesis>(msg, cancellationToken: cancellationToken).ConfigureAwait(false);

        //



        if (response.Messages.Count == 0)
        {
            await context.YieldOutputAsync(new ChatMessage(ChatRole.User, "Agent did not return a response, retry request in a bit."), cancellationToken).ConfigureAwait(false);
            return CreateFallbackResult(message.Text);
        }

        // Copy the result and attach the original prompt so downstream
        // executors can recall what the user actually asked.
        response.Result.OrigPrompt = message.Text;

        return response.Result;
    }
}