// Solution: SentinelCore
// Project:   SentinelCore.Orchestrations
// File:         GenerateHypothesisAgentExec.cs
// Author: Kyle L. Crowder
// Build Num:  091418



using SentinelCore.Contracts.Abstractions;




namespace SentinelCore.Orchestrations.Workflows.Executors;





/// <summary>
///     Generates a <see cref="SignalHypothesis" /> from a <see cref="ChatMessage" /> input
///     and reports progress and errors via the provided reporter.
/// </summary>
[YieldsOutput(typeof(SignalHypothesis))]
public sealed partial class GenerateHypothesisAgentExec : Executor
{
    private readonly AIAgent _agent;
    private readonly ISystemReporter _reporter;

    /// <summary>
    ///     Gets the human-readable name of this executor, used in log messages and diagnostics.
    /// </summary>
    public string Name { get; init; }








    /// <summary>
    ///     Initializes a new instance of the <see cref="GenerateHypothesisAgentExec" /> class.
    /// </summary>
    /// <param name="agent">The AI agent used to generate the hypothesis.</param>
    /// <param name="reporter">An <see cref="ISystemReporter" /> used to log informational messages and errors during execution.</param>
    public GenerateHypothesisAgentExec(AIAgent agent, ISystemReporter reporter) : base("GenerateHypothesis")
    {
        _agent = agent ?? throw new ArgumentNullException(nameof(agent));
        _reporter = reporter ?? throw new ArgumentNullException(nameof(reporter));
        Name = Id;
    }








    /// <summary>
    ///     Handles the generation of a hypothesis from a chat message.
    ///     Provides uniform cross-cutting concerns: logging, null validation,
    ///     cooperative cancellation propagation, and structured error handling.
    /// </summary>
    /// <param name="input">The <see cref="ChatMessage" /> to be processed by the agent.</param>
    /// <param name="context">The workflow context providing shared state.</param>
    /// <param name="cancellationToken">A token to monitor for cancellation requests.</param>
    /// <returns>A <see cref="SignalHypothesis" /> generated by the agent, or a fallback on error.</returns>
    [MessageHandler]
    public async ValueTask<SignalHypothesis> HandleChatMessageAsync(ChatMessage input, IWorkflowContext context, CancellationToken cancellationToken = default)
    {
        // --- Status: Executor start ---
        _reporter.ReportInfo($"[{Name}] Starting execution. Input type: {typeof(ChatMessage).Name}");

        // --- Null validation ---
        if (input is null)
        {
            _reporter.ReportError($"[{Name}] Input message was null. Returning fallback {nameof(SignalHypothesis)}.");
            await context.YieldOutputAsync(new ChatMessage(ChatRole.Assistant, $"[{Name}] Input message was null. Returning fallback {nameof(SignalHypothesis)}."), cancellationToken).ConfigureAwait(false);
            return CreateFallbackResult();
        }

        try
        {
            // --- Status: Begin processing ---
            _reporter.ReportInfo($"[{Name}] Processing message...");

            SignalHypothesis result = await ProcessMessageAsync(input, context, cancellationToken).ConfigureAwait(false);

            if (result is null)
            {
                _reporter.ReportError($"[{Name}] ProcessMessageAsync returned null. Using fallback {nameof(SignalHypothesis)}.");
                result = CreateFallbackResult();
            }

            // --- Status: Final output ---
            _reporter.ReportInfo($"[{Name}] Completed successfully. Output type: {nameof(SignalHypothesis)}");

            return result;
        }
        catch (OperationCanceledException)
        {
            // Cooperative cancellation must propagate — never swallow it.
            _reporter.ReportInfo($"[{Name}] Execution canceled.");
            throw;
        }
        catch (Exception ex)
        {
            // --- Robust error handling ---
            _reporter.ReportError($"[{Name}] Exception: {ex.Message}", ex);

            await context.YieldOutputAsync(new ChatMessage(ChatRole.Assistant, $"⚠️ An internal error occurred in {Name}: {ex.Message}"), cancellationToken).ConfigureAwait(false);

            _reporter.ReportInfo($"[{Name}] Returning fallback {nameof(SignalHypothesis)} due to error.");

            return CreateFallbackResult();
        }
    }








    /// <summary>
    ///     Core processing logic: invokes the agent to generate a hypothesis.
    /// </summary>
    private async ValueTask<SignalHypothesis> ProcessMessageAsync(ChatMessage input, IWorkflowContext context, CancellationToken cancellationToken)
    {
        AgentResponse response = await _agent.RunAsync(input, null, null, cancellationToken).ConfigureAwait(false);

        // TODO: Shape prompt and extract structured hypothesis from response
        return CreateFallbackResult();
    }








    /// <summary>
    ///     Creates a fallback result when the executor encounters an error or receives null input.
    /// </summary>
    private SignalHypothesis CreateFallbackResult() => new() { NextStep = NextStep.EscalateToHumanOperator, Reasoning = "Fallback: hypothesis generation did not produce a result." };
}
