// Solution: SentinelCore
// Project:   SentinelCore.UI
// File:         McpServersPage.xaml.cs
// Author: Generated by GitHub Copilot
// Build Num:  090926



using System.Windows.Controls;

using SentinelCore.UI.ViewModels;



namespace SentinelCore.UI.Views;



/// <summary>
///     Code-behind for the MCP Servers management page.
///     Responsibilities scoped to this file: ViewModel wiring.
/// </summary>
public partial class McpServersPage : Page
{
    /// <summary>
    ///     Creates the page and binds the provided view-model.
    /// </summary>
    /// <param name="viewModel">The MCP servers view-model.</param>
    /// <exception cref="ArgumentNullException">Thrown when <paramref name="viewModel" /> is <c>null</c>.</exception>
    public McpServersPage(McpServersViewModel? viewModel)
    {
        _ = viewModel ?? throw new ArgumentNullException(nameof(viewModel));
        InitializeComponent();
        DataContext = viewModel;
    }
}
