//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SentinelCoreAdmin.Properties {
    using System;

    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SentinelCoreAdmin.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ts.ItemName.
        /// </summary>
        public static string AppDisplayName {
            get {
                return ResourceManager.GetString("AppDisplayName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ShellGoBackButton.
        /// </summary>
        public static string ShellGoBackButton {
            get {
                return ResourceManager.GetString("ShellGoBackButton", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to MenuFileHeader.
        /// </summary>
        public static string ShellMenuFileHeader {
            get {
                return ResourceManager.GetString("ShellMenuFileHeader", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to MenuViewsHeader.
        /// </summary>
        public static string ShellMenuViewsHeader {
            get {
                return ResourceManager.GetString("ShellMenuViewsHeader", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to MenuItemFileExitHeader.
        /// </summary>
        public static string ShellMenuItemFileExitHeader {
            get {
                return ResourceManager.GetString("ShellMenuItemFileExitHeader", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to CoreChat.
        /// </summary>
        public static string CoreChatPageTitle
        {
            get
            {
                return ResourceManager.GetString("CoreChatPageTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to MenuItemViewsCoreChatPageHeader.
        /// </summary>
        public static string ShellMenuItemViewsCoreChatPageHeader
        {
            get
            {
                return ResourceManager.GetString("ShellMenuItemViewsCoreChatPageHeader", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to TraceLogPageBackButtonTooltip
        /// </summary>
        public static string TraceLogPageBackButtonTooltip
        {
            get
            {
                return ResourceManager.GetString("TraceLogPageBackButtonTooltip", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to TraceLogPageForwardButtonTooltip
        /// </summary>
        public static string TraceLogPageForwardButtonTooltip
        {
            get
            {
                return ResourceManager.GetString("TraceLogPageForwardButtonTooltip", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to TraceLogPageLoadingText
        /// </summary>
        public static string TraceLogPageLoadingText
        {
            get
            {
                return ResourceManager.GetString("TraceLogPageLoadingText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to TraceLogPageFaildedMessage
        /// </summary>
        public static string TraceLogPageFaildedMessage
        {
            get
            {
                return ResourceManager.GetString("TraceLogPageFaildedMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to TraceLogPageRefreshButtonTooltip
        /// </summary>
        public static string TraceLogPageRefreshButtonTooltip
        {
            get
            {
                return ResourceManager.GetString("TraceLogPageRefreshButtonTooltip", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to TraceLogPageOpenInBrowserButtonTooltip
        /// </summary>
        public static string TraceLogPageOpenInBrowserButtonTooltip
        {
            get
            {
                return ResourceManager.GetString("TraceLogPageOpenInBrowserButtonTooltip", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to MenuItemViewsTraceLogPageHeader.
        /// </summary>
        public static string ShellMenuItemViewsTraceLogPageHeader
        {
            get
            {
                return ResourceManager.GetString("ShellMenuItemViewsTraceLogPageHeader", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Settings page placeholder text.  Your app description goes here..
        /// </summary>
        public static string SettingsPageAboutText
        {
            get
            {
                return ResourceManager.GetString("SettingsPageAboutText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to About this application.
        /// </summary>
        public static string SettingsPageAboutTitle
        {
            get
            {
                return ResourceManager.GetString("SettingsPageAboutTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Choose Theme.
        /// </summary>
        public static string SettingsPageChooseThemeText
        {
            get
            {
                return ResourceManager.GetString("SettingsPageChooseThemeText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Personalization.
        /// </summary>
        public static string SettingsPagePersonalizationTitle
        {
            get
            {
                return ResourceManager.GetString("SettingsPagePersonalizationTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Privacy Statement.
        /// </summary>
        public static string SettingsPagePrivacyStatementText
        {
            get
            {
                return ResourceManager.GetString("SettingsPagePrivacyStatementText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Dark.
        /// </summary>
        public static string SettingsPageRadioButtonDarkTheme
        {
            get
            {
                return ResourceManager.GetString("SettingsPageRadioButtonDarkTheme", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Light.
        /// </summary>
        public static string SettingsPageRadioButtonLightTheme
        {
            get
            {
                return ResourceManager.GetString("SettingsPageRadioButtonLightTheme", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        public static string SettingsPageRadioButtonWindowsDefaultTheme
        {
            get
            {
                return ResourceManager.GetString("SettingsPageRadioButtonWindowsDefaultTheme", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string SettingsPageTitle
        {
            get
            {
                return ResourceManager.GetString("SettingsPageTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to MenuItemFileSettingsPageHeader.
        /// </summary>
        public static string ShellMenuItemFileSettingsPageHeader
        {
            get
            {
                return ResourceManager.GetString("ShellMenuItemFileSettingsPageHeader", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to StatusUnauthorized.
        /// </summary>
        public static string StatusUnauthorized {
            get {
                return ResourceManager.GetString("StatusUnauthorized", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to StatusNoNetworkAvailable.
        /// </summary>
        public static string StatusNoNetworkAvailable {
            get {
                return ResourceManager.GetString("StatusNoNetworkAvailable", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to StatusLoginFails.
        /// </summary>
        public static string StatusLoginFails {
            get {
                return ResourceManager.GetString("StatusLoginFails", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to LogInPageTitle.
        /// </summary>
        public static string LogInPageTitle {
            get {
                return ResourceManager.GetString("LogInPageTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to LogInButton.
        /// </summary>
        public static string LogInButton {
            get {
                return ResourceManager.GetString("LogInButton", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to LogInAccountTypeHeader.
        /// </summary>
        public static string LogInAccountTypeHeader {
            get {
                return ResourceManager.GetString("LogInAccountTypeHeader", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to LogInAccountTypeAadAndPersonal.
        /// </summary>
        public static string LogInAccountTypeAadAndPersonal {
            get {
                return ResourceManager.GetString("LogInAccountTypeAadAndPersonal", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to LogInAccountTypePersonalMs.
        /// </summary>
        public static string LogInAccountTypePersonalMs {
            get {
                return ResourceManager.GetString("LogInAccountTypePersonalMs", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to LogInAccountTypeAadMultipleOrgs.
        /// </summary>
        public static string LogInAccountTypeAadMultipleOrgs {
            get {
                return ResourceManager.GetString("LogInAccountTypeAadMultipleOrgs", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to LogInAccountTypeAadSingleOrg.
        /// </summary>
        public static string LogInAccountTypeAadSingleOrg {
            get {
                return ResourceManager.GetString("LogInAccountTypeAadSingleOrg", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to SettingsPageUserTitle.
        /// </summary>
        public static string SettingsPageUserTitle {
            get {
                return ResourceManager.GetString("SettingsPageUserTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to SettingsPageLogOutButtonText.
        /// </summary>
        public static string SettingsPageLogOutButtonText {
            get {
                return ResourceManager.GetString("SettingsPageLogOutButtonText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Trace Log.
        /// </summary>
        public static string TraceLogPageTitle {
            get {
                return ResourceManager.GetString("TraceLogPageTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Log file:.
        /// </summary>
        public static string TraceLogPageFilePathLabel {
            get {
                return ResourceManager.GetString("TraceLogPageFilePathLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Open log folder.
        /// </summary>
        public static string TraceLogPageOpenFolderTooltip {
            get {
                return ResourceManager.GetString("TraceLogPageOpenFolderTooltip", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to _Case Management.
        /// </summary>
        public static string ShellMenuCaseManagementHeader {
            get {
                return ResourceManager.GetString("ShellMenuCaseManagementHeader", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Case List.
        /// </summary>
        public static string ShellMenuItemCaseListPageHeader {
            get {
                return ResourceManager.GetString("ShellMenuItemCaseListPageHeader", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Create Case.
        /// </summary>
        public static string ShellMenuItemCreateCasePageHeader {
            get {
                return ResourceManager.GetString("ShellMenuItemCreateCasePageHeader", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Case Detail.
        /// </summary>
        public static string ShellMenuItemCaseDetailPageHeader {
            get {
                return ResourceManager.GetString("ShellMenuItemCaseDetailPageHeader", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Case List.
        /// </summary>
        public static string CaseListPageTitle {
            get {
                return ResourceManager.GetString("CaseListPageTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Create Case.
        /// </summary>
        public static string CreateCasePageTitle {
            get {
                return ResourceManager.GetString("CreateCasePageTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Case Detail.
        /// </summary>
        public static string CaseDetailPageTitle {
            get {
                return ResourceManager.GetString("CaseDetailPageTitle", resourceCulture);
            }
        }
    }
}
